version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages
        description: "Raw Telegram messages loaded from the data lake"
        columns:
          - name: message_id
            description: "Unique message ID"
          - name: channel_name
            description: "Telegram channel name"
          - name: message_date
            description: "Timestamp of the message"

models:
  - name: stg_telegram_messages
    description: "Cleaned and standardized staging model of raw Telegram messages."
    columns:
      - name: message_id
        tests:
          - not_null
          - unique
      - name: channel_name
        tests:
          - not_null
      - name: message_date
        tests:
          - not_null
      - name: view_count
        tests:
          - not_null
      - name: forward_count
        tests:
          - not_null
