version: 2

sources:
  - name: telegram
    database: medical_telegram_warehouse
    schema: raw
    tables:
      - name: telegram_messages
      - name: yolo_detections

models:
  - name: dim_channels
    description: "Telegram channel dimension"
    columns:
      - name: channel_key
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Date dimension"
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "Fact table of Telegram messages"
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_key
      - name: date_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_dates')
                field: date_key

  - name: fct_image_detections
    description: "Fact table linking YOLO object detections"
    columns:
      - name: detection_key
        tests:
          - unique
          - not_null
      - name: message_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('fct_messages')
                field: message_id
      - name: channel_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_key
      - name: primary_category
        tests:
          - not_null
          - accepted_values:
              values:
                - promotional
                - product_display
                - lifestyle
                - other
      - name: confidence_score
        tests:
          - not_null
